on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

name: Update R Package Dev Branch

jobs:
  testing:
    name: r-cran-branch
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::testthat, any::decor

      - name: Create CRAN-formatted source package in stochtree_cran subfolder
        run: |
          Rscript cran-bootstrap.R
      
      - name: Deploy to CRAN dev branch
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: r-dev
          folder: stochtree_cran